### ISSUE TITLE
Make fails in 'ws' folder

### ISSUE THREAD

**Issue by myreauks** [phorton1/circle-prh#1]
Hi!

I am interested in your crude port of the LCD library, and would like to do some testing with it. All my make attempts fail in the 'ws'-folder with the following errors. Do you know what might go wrong here?

Best,
Miro

In file included from ../../_prh/ws/wsWindow.h:17,
                 from ../../_prh/ws/wsTopWindow.h:10,
                 from ../../_prh/ws/wsApp.h:10,
                 from ../../_prh/system/std_kernel.h:90,
                 from control_wm8731.cpp:33:
../../_prh/ws/wsDC.h:33:21: error: expected ')' before '*' token
   33 |    CScreenDeviceBase *pScreen) :
      |                     ^~
      |                     )
../../_prh/ws/wsDC.h:32:7: note: to match this '('
   32 |   wsDC(
      |       ^
../../_prh/ws/wsDC.h:50:3: error: 'CScreenDeviceBase' does not name a type; did you mean 'CScreenDevice'?
   50 |   CScreenDeviceBase *getScreen()  { return m_pScreen; }
      |   ^~~~~~~~~~~~~~~~~
      |   CScreenDevice
../../_prh/ws/wsDC.h:122:3: error: 'CScreenDeviceBase' does not name a type; did you mean 'CScreenDevice'?
  122 |   CScreenDeviceBase *m_pScreen;
      |   ^~~~~~~~~~~~~~~~~
      |   CScreenDevice
../../_prh/ws/wsDC.h: In member function 'void wsDC::setPixel(s32, s32, wsColor)':
../../_prh/ws/wsDC.h:54:6: error: 'm_pScreen' was not declared in this scope
   54 |    { m_pScreen->SetPixel(x,y,color); }
      |      ^~~~~~~~~
In file included from ../../_prh/system/std_kernel.h:90,
                 from control_wm8731.cpp:33:
../../_prh/ws/wsApp.h: At global scope:
../../_prh/ws/wsApp.h:32:4: error: 'CScreenDeviceBase' has not been declared
   32 |    CScreenDeviceBase *pScreen,
      |    ^~~~~~~~~~~~~~~~~
../../_prh/ws/wsApp.h:33:4: error: 'CTouchScreenBase' has not been declared
   33 |    CTouchScreenBase  *pTouch,
      |    ^~~~~~~~~~~~~~~~
../../_prh/ws/wsApp.h:72:3: error: 'CScreenDeviceBase' does not name a type; did you mean 'CScreenDevice'?
   72 |   CScreenDeviceBase *m_pScreen;
      |   ^~~~~~~~~~~~~~~~~
      |   CScreenDevice
../../_prh/ws/wsApp.h:73:3: error: 'CTouchScreenBase' does not name a type; did you mean 'CTouchScreenDevice'?
   73 |   CTouchScreenBase  *m_pTouch;
      |   ^~~~~~~~~~~~~~~~
      |   CTouchScreenDevice
make[1]: *** [../../Rules.mk:142: control_wm8731.o] Error 1

**Comment by phorton1** [comment]
Sorry to answer so late, but it looks like you were compiling against the "official" circle repo.  This repo requires that you compile against the https://github.com/phorton1/circle repo.
